version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: recru-task-app
    container_name: recru-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - recru-network

  nginx:
    image: nginx:alpine
    container_name: recru-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - recru-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: recru-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: tmdb_service
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33061:3306"
    networks:
      - recru-network

networks:
  recru-network:
    driver: bridge
